#!/bin/bash
#use genion to change ion concentrations in whatever files you need
cur_dir=$(pwd)
echo $cur_dir
top_in=$cur_dir"/Lau-core-files/topol.top" #topology file
gro_out=$cur_dir"/cood_out.gro" #output coordinate file 
run_file=$cur_dir"/en_min.tpr" #a tpr file generated by grommpp. 

pos_i=26 # number of positive ions -np
p_name="POT" #positive ion name

neg_i=26 #negative ion number -nn
n_name="CLA" #negative ion name
#don't use -conc as it calculates salt concentration from the volume of the cell, not the moles we need

#echo "topology = $top_in \n tpr = $run_file \n output = $gro_out \n positive ions = $pos_i $p_name \n negative ions = $neg_i $n_name"

gmx genion -s $run_file -p $top_in -n index.ndx -o $gro_out -np $pos_i -pname $p_name -pq 1 -nn $neg_i -nname $n_name -nq -1

echo "dont forget to check the topology file to make sure ion numbers saved correctly. (It rarely does)"